INSERT INTO public.properties (
    villa_number,
    owner_customer_id,
    project_id,
    plan_id,
    is_corner,
    is_lake_front,
    is_park_front,
    is_beach,
    is_market,
    property_status,
    community_id
)
SELECT *
FROM (
    VALUES
        ('266', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('267', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('268', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('269', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('270', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('271', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('272', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('273', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('274', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('275', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('276', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('277', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('278', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('279', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('280', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('281', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('282', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('283', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('284', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('285', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('286', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('287', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('288', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('289', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('290', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('291', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('292', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('293', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('294', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('295', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('296', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('297', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('298', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('299', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('300', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('301', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('302', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('303', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('304', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('305', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('306', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('307', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('308', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('309', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('310', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('311', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('312', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('313', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('314', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('315', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('316', NULL, 2, 46, false, false, false, false, false, 'Off-Market', 4),
        ('317', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('318', NULL, 2, 48, false, false, false, false, false, 'Off-Market', 4),
        ('319', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('320', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4),
        ('321', NULL, 2, 47, false, false, false, false, false, 'Off-Market', 4)
) AS v(
    villa_number,
    owner_customer_id,
    project_id,
    plan_id,
    is_corner,
    is_lake_front,
    is_park_front,
    is_beach,
    is_market,
    property_status,
    community_id
)
WHERE NOT EXISTS (
    SELECT 1
    FROM public.properties p
    WHERE p.villa_number = v.villa_number
      AND p.community_id = v.community_id
);